apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/operator-framework/operator-lifecycle-manager.git
    targetRevision: v0.46.0
    path: deploy/chart
    helm:
      releaseName: olm
      valueFiles:
        - ../upstream/values.yaml
      valuesObject:
        olm:
          image:
            ref: quay.io/operator-framework/olm@sha256:4404599eb7b7736bdbd0f36260a60599f32acb6edeaf7d0c54bb10b36619e5fe
        catalog:
          image:
            ref: quay.io/operator-framework/olm@sha256:4404599eb7b7736bdbd0f36260a60599f32acb6edeaf7d0c54bb10b36619e5fe
          opmImageArgs: --opmImage=quay.io/operator-framework/opm@sha256:e5a6220603fb4504d58c6e3e488386b817e3695c906a62ee0370b5faedc3799a
        package:
          image:
            ref: quay.io/operator-framework/olm@sha256:4404599eb7b7736bdbd0f36260a60599f32acb6edeaf7d0c54bb10b36619e5fe
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
